apiVersion: "v1"
kind: "LimitRange"
metadate: 
  name: "project-limits"
spec: 
  limits: 
    - type: "Container"
      max: 
        cpu: "1000m"
        memory: "1Gi"
      min: 
        cpu: "250m"
        memory: "256Mi"
      default: 
        cpu: "500m"
        memory: "512Mi"
      defaultRequest: 
        cpu: "250m"
        memory: "256Mi"
    - type: "Pod"
      max: 
        cpu: "1000m"
        memory: "512Mi"
      min: 
        cpu: "250m"
        memory: "256Mi"
    - type: "PersistentVolumeClaim"
      min: 
        storage: "2Gi"
      max: 
        storage: "10Gi"
    - type: openshift.io/Image
      max:
        storage: "1Gi"
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 20
        openshift.io/images: 30