apiVersion: v1
kind: PersistentVolume
metadata: 
  name: example-volume
spec: 
  capacity: 
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /var/export/example
    server: nfs.example.com