#!/bin/bash
dir_name=$1
export_dir="/var/export/${dir_name}"
export_file="/etc/exports.d/${dir_name}.exports"

echo "Your directory will be located at ..."
echo ${export_dir}
echo "Your NFS export file will be located at ..."
echo ${export_file}

if [ -d ${export_dir}]; then
	echo "Directory  ${export_dir} already exists..."
  else
	echo "Stard create directory..."
	mkdir -p ${export_dir}
	chown nfsnobody:nfsnobody ${export_dir}
	chmod 700 ${export_dir}
	echo "Directory is created..."
fi

if [ -f ${export_file}]; then
	echo "Export file ${export_file} already exists..."
  else
    echo "${export_dir} *(rw,async,all_squash)" > ${export_file}
	exportfs -a 
fi
  
  